### ISSUE TITLE
Handling of subsumes in DafnyProjectManager 

### ISSUE THREAD

**Issue by sgrebing** [mattulbrich/dive#125]
When having different Dafnyfiles in the "subsume" setting they are not added to the project's Dafynfiles and are therefore not loaded in the GUI.

Is this an intentional behaviour?

Steps to reproduce:
````
Add 
// ---- Automatically generated settings ----
//\\ settings {
//\\    "KeY Timeout" = "10",
//\\    "Dafny Timeout" = "5",
//\\    "SMT Timeout" = "20",
//\\    "Sequent Generation Type" = "ass-simp"
//\\ }
//\\ subsume "test.dfy"
//\\ subsume "test2.dfy"
// ---- End of settings ----
````
 To the test.dfy in the docs/simple/test.dfy file and load this file.

I thought test2.dfy should be loaded too.

Using a confix.xml both files are loaded. What is the inteded behaviour?

**Comment by mattulbrich** [comment]
There was an additional commit on this issue on the branch, but it has been fixed elsewhere.
