### ISSUE TITLE
Script parser errors: wrong locations

### ISSUE THREAD

**Issue by mattulbrich** [mattulbrich/dive#139]
When there is a parser error inside the argument of a script command, the location within the argument is treated as error location.

Locations in script arguments should be translated into script-relative locations.

In the screenshot below, the error is in line 9 (`=` instead of `==`), yet the error is reported in line 1 (because the error is in line 1:15) of the argument.

![Screenshot_2019-06-19_17-08-22](https://user-images.githubusercontent.com/17046629/59777383-de213e80-92b4-11e9-84c7-52a93a4da582.png)

**Comment by JonasKlamroth** [comment]
this works fine as far as i tested it. so ill close it
