### ISSUE TITLE
Script parser: Missing "match" is not reported

### ISSUE THREAD

**Issue by mattulbrich** [mattulbrich/dive#141]
This is related to #140 and perhaps has the same source.

When the keyword "match" is missing before the branch label, then branches are silently ignored.

Load standard example, choose `List.getAt/InitInv[idxInv]`
and run the script
````
andRight on='|- ... ((?match: idx₁ >= 0 && idx₁ <= pos)) ...';
cases {
	case "case 1": {
		stupidCode ;
	}
	case "case 2": {
		stupidCode ;
	}
}
````

No error is raised.

Refers to 39a8d27e9bd2240716a95f9267c9294689e117ee

**Comment by mattulbrich** [comment]
current master (d1b1929465303638a63579856187ca5587395395): does not work

**Comment by JonasKlamroth** [comment]
works on current master ( 56fd73ef)
