### ISSUE TITLE
Add vstte release

### ISSUE THREAD

**Issue by JonasKlamroth** [mattulbrich/dive#143]
There should be a release called vstte version.

**Comment by mattulbrich** [comment]
This last issue has been fixed on `b1fdc87723739682c67426fcd1a9f7975fd43111`.

**Comment by sgrebing** [comment]
Please review whether I can publish the pre release for VSTTE. i added the latest vstte-jar file to it which can also be downloaded from the webpage

**Comment by JonasKlamroth** [comment]
this is not relevant anymore
