### ISSUE TITLE
Branchcount is not shown anymore since ruie refactoring

### ISSUE THREAD

**Issue by sgrebing** [mattulbrich/dive#151]
Since the rule refactoring, the branchcount of most of the branching rules is 0 in the GUI. This was a fundamental design idea.

The information is required from considerApplication. For example looking deeper into the rules branchCut and replaceCut is set to 0.

**Comment by mattulbrich** [comment]
apparently, this was so even before the change. Does the `'?'` solution solve this issue, @sgrebing ?
