### ISSUE TITLE
error "unkown identifier new" when new objects on heap

### ISSUE THREAD

**Issue by JonasKlamroth** [mattulbrich/dive#155]
when a new object is created no rules are applicable anymore on the sequent. 

Minimal example to reproduce:
```
class Node {
  var value: int
}

method test() {
   var node := new Node;
   assert node != null;
}
```

This produces 1 pvc. Apply any rule (e.g. substitute) on the succedent and an error occurs:
"Unkown identifier $new"

**Comment by SpringVaS** [comment]
Same error with "$aheap"
![aheap](https://user-images.githubusercontent.com/15802245/82983793-149d2880-9ff1-11ea-9439-176190fab258.png)

**Comment by mattulbrich** [comment]
I have just rediscovered there is a class `ResolveUnicodeVisitor` which allows one to use the unicode characters in inputs. If that is already there it seems best to make that accessible ...

**Comment by SpringVaS** [comment]
Fix is on the master. Could not reproduce this exact issue.
