### ISSUE TITLE
Chained relational expressions are not parsed correctly.

### ISSUE THREAD

**Issue by mattulbrich** [mattulbrich/dive#176]
The following should be parsable in Dafny, but are not all in DIVE:

`lemma m(x: int, y:int, z:int)`
* [x] `requires x == y == z`
* [x] `requires x > y > z`
* [x] `requires x > y == z`
* [x] `requires x == y >= z`
* [x] `requires (x > 0) == true`
* [x] `requires (x == 0) == true`

`{}`

**Comment by SpringVaS** [comment]
Why is here the `required` keyword used, rather than `ensures`?

**Comment by mattulbrich** [comment]
Because it does not matter. The term `x>y>z` must be digested by the parser and it is irrelevant in what context. Hence, requires is as good as ensures or any other construct.

**Comment by SpringVaS** [comment]
I see. `requires` does not load the lemma as a rule in DIVE, though. But that has nothing to do with this issue, so i was confused.
