### ISSUE TITLE
Dafny interpreter

### ISSUE THREAD

**Issue by SpringVaS** [mattulbrich/dive#179]
1) Syntax s := s[i := v] for updating sequences not supported
2) Dash minus '|-' is read as turnstile '⊢'. Particularly in 's := s[0..|s|-1]' This is not expected behavior.
![sequpdate](https://user-images.githubusercontent.com/15802245/84251833-2eb92980-ab0e-11ea-8186-2d70a0fd4e9e.png)
![readasstencil](https://user-images.githubusercontent.com/15802245/84251844-324cb080-ab0e-11ea-94e5-e9176a4d8b2e.png)

**Comment by mattulbrich** [comment]
Can you paste the stacktrace as text please. I can't read the message

**Comment by SpringVaS** [comment]
Fixed in #182 and #183
