### ISSUE TITLE
Exception on highlighting code with mismatched braces

### ISSUE THREAD

**Issue by SpringVaS** [mattulbrich/dive#180]
It appears that a style range is computed wrong when the curly braces in the code don't match. E. g. removing lines. It might be enough to catch the exception.
![exception](https://user-images.githubusercontent.com/15802245/84254185-2ca49a00-ab11-11ea-8769-58fe15cd14c7.png)

**Comment by JonasKlamroth** [comment]
can you provide steps to reproduce?
if i try to load a dafny file with mismatched curly braces i do get an exception pointing exactly this out which to me seems like the expected behaviour. Do you have a sample code to show this bug?

**Comment by SpringVaS** [comment]
Could not reproduce. Closing it.
